create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
create table products (bid integer not null, bid_winner integer, owner_id integer not null, product_id integer not null, status integer, create_date datetime(6) not null, end_date datetime(6) not null, product_category varchar(255), product_description varchar(255), product_name varchar(255) not null, primary key (product_id)) engine=InnoDB;
create table products_seq (next_val bigint) engine=InnoDB;
insert into products_seq values ( 1 );
create table users (mobile_no integer, user_id integer not null, email varchar(255) not null, hostel varchar(255), name varchar(255), primary key (user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
